FROM nexus.forge-dc.cloudmi.minint.fr/node:14-alpine

LABEL maintainer=STI
ARG TOKENARG

# récupérer le certificat ssl de la forge
COPY forge-dc.cloudmi.minint.fr.pem /usr/local/share/ca-certificates/forge-dc.cloudmi.minint.fr.pem
 
# Créer le fichier de configuration
RUN npm config set cafile "forge-dc.cloudmi.minint.fr.pem"
RUN npm config set registry "https://nexus.forge-dc.cloudmi.minint.fr/repository/npm/"
RUN npm config set _auth "${TOKENARG}"
RUN npm set strict-ssl false

# Dossier de travail par défaut
WORKDIR /app

# installe un simple serveur http pour servir un contenu statique, ne va servir ici que pour assurer le lancement du container
RUN npm install -g http-server 

#Installation de vue-vli
RUN npm install -g @vue/cli
RUN npm install -g @vue/cli-service

# Ouverture du port
EXPOSE 8000

# copie 'package.json' et 'package-lock.json' (si disponible)
COPY package*.json ./

CMD [ "npm", "run" , "dev"]


